/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs499_ophthalmology_emr;

/**
 *
 * @author angelaallison
 */
public class HomeWindow extends javax.swing.JFrame {

    /**
     * Creates new form HomeWindow
     */
    public HomeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jTextField2 = new javax.swing.JTextField();
        practiceManagement = new javax.swing.JButton();
        patientPortal = new javax.swing.JButton();
        eyeTestResults = new javax.swing.JButton();
        ocularEyeExams = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField2.setFont(new java.awt.Font("Courier", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 204, 51));
        jTextField2.setText("Welcome to EMR");

        practiceManagement.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        practiceManagement.setForeground(new java.awt.Color(255, 204, 51));
        practiceManagement.setText("Practice Management");
        practiceManagement.setToolTipText("");
        practiceManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                practiceManagementActionPerformed(evt);
            }
        });

        patientPortal.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        patientPortal.setForeground(new java.awt.Color(255, 204, 51));
        patientPortal.setText("Patient Portal");
        patientPortal.setToolTipText("");
        patientPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientPortalActionPerformed(evt);
            }
        });

        eyeTestResults.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        eyeTestResults.setForeground(new java.awt.Color(255, 204, 51));
        eyeTestResults.setText("Eye Test Results");
        eyeTestResults.setToolTipText("");
        eyeTestResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyeTestResultsActionPerformed(evt);
            }
        });

        ocularEyeExams.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        ocularEyeExams.setForeground(new java.awt.Color(255, 204, 51));
        ocularEyeExams.setText("Ocular Eye Examinations");
        ocularEyeExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocularEyeExamsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(366, 366, 366))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(patientPortal)
                        .addGap(134, 134, 134)
                        .addComponent(eyeTestResults)
                        .addGap(239, 239, 239))))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(ocularEyeExams)
                .addGap(160, 160, 160)
                .addComponent(practiceManagement)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ocularEyeExams)
                            .addComponent(practiceManagement))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eyeTestResults)
                            .addComponent(patientPortal))
                        .addGap(309, 309, 309))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientPortalActionPerformed
        // TODO add your handling code here:
        
            PatientPortalWindow w = new PatientPortalWindow();
            w.setVisible(true);
       
    }//GEN-LAST:event_patientPortalActionPerformed

    private void eyeTestResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyeTestResultsActionPerformed
        // TODO add your handling code here:
            
            EyeTestResults eyeTestRWindow = new EyeTestResults();
            eyeTestRWindow.setVisible(true);
    }//GEN-LAST:event_eyeTestResultsActionPerformed

    private void ocularEyeExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocularEyeExamsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocularEyeExamsActionPerformed

    private void practiceManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_practiceManagementActionPerformed
        // TODO add your handling code here:
        
        PracticeMangment practiceManagment = new PracticeMangment();
        practiceManagment.setVisible(true);
    }//GEN-LAST:event_practiceManagementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eyeTestResults;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton ocularEyeExams;
    private javax.swing.JButton patientPortal;
    private javax.swing.JButton practiceManagement;
    // End of variables declaration//GEN-END:variables
}
