/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs499_ophthalmology_emr;

import javax.swing.JOptionPane;

/**
 *
 * @author angelaallison
 */
public class VisualAcuity extends javax.swing.JPanel {
    
    private MainDashboard mainDash;
    private DataBaseManager dataBase;
    private EyeTestResults eyeTestResults;
    private Patient activePatient;
    private Appointment activeAppointment;
    
         
    public VisualAcuity(MainDashboard mD ) {
     
     activePatient = null;
     mainDash = mD;
     dataBase = DataBaseManager.getInstance();
    
     initComponents();
     
    }
    public void loadEyeTestResults(){
        
        activePatient = mainDash.getActivePatient();
        activeAppointment = mainDash.getActiveAppointment();
		Integer apptID = activeAppointment.getApptID();
		
		eyeTestResults = dataBase.getExamResultsByApptID(apptID);
		if (eyeTestResults == null)
			eyeTestResults = dataBase.getNewEyeTestResults(activePatient.getPatientID(), activeAppointment.getApptID());
		mainDash.setActiveResults(eyeTestResults);
		
		dccODComboBox.setSelectedItem(eyeTestResults.getDccOD());
		dccOSComboBox.setSelectedItem(eyeTestResults.getDccOS());
		dccOUComboBox.setSelectedItem(eyeTestResults.getDccOU());
		dscODComboBox.setSelectedItem(eyeTestResults.getDscOD());
		dscOSComboBox.setSelectedItem(eyeTestResults.getDscOS());
		dscOUComboBox.setSelectedItem(eyeTestResults.getDscOU());
		
		dccODphComboBox.setSelectedItem(eyeTestResults.getDccODph());
		dccOSphComboBox.setSelectedItem(eyeTestResults.getDccOSph());
		dccOUphComboBox.setSelectedItem(eyeTestResults.getDccOUph());
		dscODphComboBox.setSelectedItem(eyeTestResults.getDscODph());
		dscOSphComboBox.setSelectedItem(eyeTestResults.getDscOSph());
		dscOUphComboBox.setSelectedItem(eyeTestResults.getDscOUph());
		
		nccODComboBox.setSelectedItem(eyeTestResults.getNccOD());
		nccOSComboBox.setSelectedItem(eyeTestResults.getNccOS());
		nccOUComboBox.setSelectedItem(eyeTestResults.getNccOU());
		nscODComboBox.setSelectedItem(eyeTestResults.getNscOD());
		nscOSComboBox.setSelectedItem(eyeTestResults.getNscOS());
		nscOUComboBox.setSelectedItem(eyeTestResults.getNscOU());

		nccODphComboBox.setSelectedItem(eyeTestResults.getNccODph());
		nccOSphComboBox.setSelectedItem(eyeTestResults.getNccOSph());
		nccOUphComboBox.setSelectedItem(eyeTestResults.getNccOUph());
		nscODphComboBox.setSelectedItem(eyeTestResults.getNscODph());
		nscOSphComboBox.setSelectedItem(eyeTestResults.getNscOSph());
		nscOUphComboBox.setSelectedItem(eyeTestResults.getNscOUph());
		
		sphereODTXTF.setText(eyeTestResults.getSphereOD().toString());
		axisODTXTF.setText(eyeTestResults.getAxisOD().toString());
		cylinderODTXTF.setText(eyeTestResults.getCylinderOD().toString());
		prismODTXTF.setText(eyeTestResults.getPrismOD().toString());
		prismBaseODTXTF.setText(eyeTestResults.getPrismBaseOD().toString());
		addODTXTF.setText(eyeTestResults.getAddOD().toString());
		
		sphereOSTXTF.setText(eyeTestResults.getSphereOS().toString());
		axisOSTXTF.setText(eyeTestResults.getAxisOS().toString());
		cylinderOSTXTF.setText(eyeTestResults.getCylinderOS().toString());
		prismOSTXTF.setText(eyeTestResults.getPrismOS().toString());
		prismBaseOSTXTF.setText(eyeTestResults.getPrismBaseOS().toString());
		addOSTXTF.setText(eyeTestResults.getAddOS().toString());
		
		dataBase.save(eyeTestResults);
    } 
	
		private Boolean validateFloat(String theString)
	{
		Boolean isValid = true;
		Boolean decimalFound = false;
		Integer remainingDecimalPlaces = 2;
		
		String trimmedFloat = "";
		
		for (Integer i=0; i < theString.length(); i++)
		{
			if (Character.isDigit(theString.charAt(i)))
			{
				if (decimalFound)
				{
					--remainingDecimalPlaces;
					if (remainingDecimalPlaces < 0)
					{
						isValid = false;
					}
				}
				trimmedFloat += theString.charAt(i);
			}
			
			
			
			if (theString.charAt(i) == '.')
			{
				if (decimalFound == true)
				{
					isValid = false;
				}
				else
				{
					decimalFound = true;
				}
			}
		}
		if (remainingDecimalPlaces > 0)
		{
			//isValid = false;
		}
		if (trimmedFloat.equals(""))
		{
			isValid = false;
		}
		return (isValid && decimalFound);
	}
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nccODComboBox = new javax.swing.JComboBox<>();
        nccOSComboBox = new javax.swing.JComboBox<>();
        nccOUComboBox = new javax.swing.JComboBox<>();
        nscODComboBox = new javax.swing.JComboBox<>();
        nscOSComboBox = new javax.swing.JComboBox<>();
        nscOUComboBox = new javax.swing.JComboBox<>();
        nccODphComboBox = new javax.swing.JComboBox<>();
        nccOSphComboBox = new javax.swing.JComboBox<>();
        nccOUphComboBox = new javax.swing.JComboBox<>();
        nscODphComboBox = new javax.swing.JComboBox<>();
        nscOUphComboBox = new javax.swing.JComboBox<>();
        nscOSphComboBox = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        dccODComboBox = new javax.swing.JComboBox<>();
        dccOSComboBox = new javax.swing.JComboBox<>();
        dccOUComboBox = new javax.swing.JComboBox<>();
        dscODComboBox = new javax.swing.JComboBox<>();
        dscOSComboBox = new javax.swing.JComboBox<>();
        dscOUComboBox = new javax.swing.JComboBox<>();
        dccODphComboBox = new javax.swing.JComboBox<>();
        dccOSphComboBox = new javax.swing.JComboBox<>();
        dccOUphComboBox = new javax.swing.JComboBox<>();
        dscODphComboBox = new javax.swing.JComboBox<>();
        dscOUphComboBox = new javax.swing.JComboBox<>();
        dscOSphComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        correctiveLabel = new javax.swing.JLabel();
        rangeLabel = new javax.swing.JLabel();
        prismBaseLabel = new javax.swing.JLabel();
        cylinderLabel2 = new javax.swing.JLabel();
        prismLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        axisLabel = new javax.swing.JLabel();
        sphereOSTXTF = new javax.swing.JTextField();
        sphereLabel = new javax.swing.JLabel();
        rangeLabel1 = new javax.swing.JLabel();
        sphereLabel1 = new javax.swing.JLabel();
        addOSTXTF = new javax.swing.JTextField();
        cylinderLabel3 = new javax.swing.JLabel();
        axisOSTXTF = new javax.swing.JTextField();
        prismBaseLabel1 = new javax.swing.JLabel();
        cylinderOSTXTF = new javax.swing.JTextField();
        addLabel1 = new javax.swing.JLabel();
        prismOSTXTF = new javax.swing.JTextField();
        prismLabel2 = new javax.swing.JLabel();
        prismBaseOSTXTF = new javax.swing.JTextField();
        sphereLabel2 = new javax.swing.JLabel();
        sphereODTXTF = new javax.swing.JTextField();
        sphereLabel3 = new javax.swing.JLabel();
        axisLabel1 = new javax.swing.JLabel();
        addLabel2 = new javax.swing.JLabel();
        axisODTXTF = new javax.swing.JTextField();
        cylinderODTXTF = new javax.swing.JTextField();
        prismODTXTF = new javax.swing.JTextField();
        prismBaseODTXTF = new javax.swing.JTextField();
        addODTXTF = new javax.swing.JTextField();
        saveBttn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(57, 113, 177));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setPreferredSize(new java.awt.Dimension(1700, 887));

        titleBar.setBackground(new java.awt.Color(32, 33, 35));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Visual Acuity");

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1700, Short.MAX_VALUE)
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(1286, 704));

        jPanel7.setBackground(new java.awt.Color(32, 33, 35));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 5, 4, 5, new java.awt.Color(253, 252, 233)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NccOD");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NccOS");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NccOU");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NscOD");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NscOS");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NscOU");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NccOSPH");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NccODPH");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NccOUPH");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NscODPH");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NscOUPH");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NscOSPH");

        nccODComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        nccODComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nccODComboBoxActionPerformed(evt);
            }
        });

        nccOSComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        nccOSComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nccOSComboBoxActionPerformed(evt);
            }
        });

        nccOUComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        nccOUComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nccOUComboBoxActionPerformed(evt);
            }
        });

        nscODComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        nscODComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nscODComboBoxActionPerformed(evt);
            }
        });

        nscOSComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        nscOSComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nscOSComboBoxActionPerformed(evt);
            }
        });

        nscOUComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        nscOUComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nscOUComboBoxActionPerformed(evt);
            }
        });

        nccODphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        nccODphComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nccODphComboBoxActionPerformed(evt);
            }
        });

        nccOSphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        nccOSphComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nccOSphComboBoxActionPerformed(evt);
            }
        });

        nccOUphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        nccOUphComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nccOUphComboBoxActionPerformed(evt);
            }
        });

        nscODphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        nscODphComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nscODphComboBoxActionPerformed(evt);
            }
        });

        nscOUphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        nscOUphComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nscOUphComboBoxActionPerformed(evt);
            }
        });

        nscOSphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        nscOSphComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nscOSphComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nscOUComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nccOSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nccOUComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nscODComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nscOSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nccODComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nscODphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nscOUphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nscOSphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nccODphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nccOSphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nccOUphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nccODComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nccODphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nccOSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nccOSphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nccOUComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nccOUphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nscODComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nscODphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nscOSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nscOSphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nscOUComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nscOUphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel8.setBackground(new java.awt.Color(32, 33, 35));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 5, 4, 5, new java.awt.Color(253, 252, 233)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DccOD");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("DccOS");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("DccOU");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("DscOD");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("DscOS");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("DscOU");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("DccOSPH");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("DccODPH");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("DccOUPH");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("DscODPH");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("DscOUPH");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("DscOSPH");

        dccODComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        dccODComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dccODComboBoxActionPerformed(evt);
            }
        });

        dccOSComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        dccOSComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dccOSComboBoxActionPerformed(evt);
            }
        });

        dccOUComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        dccOUComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dccOUComboBoxActionPerformed(evt);
            }
        });

        dscODComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        dscODComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dscODComboBoxActionPerformed(evt);
            }
        });

        dscOSComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        dscOSComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dscOSComboBoxActionPerformed(evt);
            }
        });

        dscOUComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        dscOUComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dscOUComboBoxActionPerformed(evt);
            }
        });

        dccODphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        dccODphComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dccODphComboBoxActionPerformed(evt);
            }
        });

        dccOSphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        dccOSphComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dccOSphComboBoxActionPerformed(evt);
            }
        });

        dccOUphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        dccOUphComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dccOUphComboBoxActionPerformed(evt);
            }
        });

        dscODphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        dscODphComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dscODphComboBoxActionPerformed(evt);
            }
        });

        dscOUphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        dscOUphComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dscOUphComboBoxActionPerformed(evt);
            }
        });

        dscOSphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT CHECKED", "20/10", "20/12.5", "20/16", "20/20", "20/ 25", "20/32", "20/40", "20/50", "20/63", "20/80", "20/100", "20/125", "20/160", "20/200" }));
        dscOSphComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dscOSphComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dccOSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dccOUComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dscODComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dscOSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dscOUComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dccODComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dccOUphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dscOUphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dscOSphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dscODphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dccOSphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dccODphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dccODComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dccODphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dccOSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dccOSphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dccOUComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dccOUphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dscODComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dscODphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dscOSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dscOSphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dscOUComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dscOUphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 5, 4, 5, new java.awt.Color(253, 252, 233)));
        jPanel2.setForeground(new java.awt.Color(253, 252, 233));

        jPanel3.setBackground(new java.awt.Color(135, 206, 250));

        correctiveLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        correctiveLabel.setForeground(new java.awt.Color(32, 33, 35));
        correctiveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correctiveLabel.setText("Corrective Lenses");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(correctiveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(correctiveLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        rangeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        rangeLabel.setForeground(new java.awt.Color(255, 255, 255));
        rangeLabel.setText("OD:");
        rangeLabel.setToolTipText("");

        prismBaseLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prismBaseLabel.setForeground(new java.awt.Color(255, 255, 255));
        prismBaseLabel.setText("Prism Base: ");
        prismBaseLabel.setToolTipText("");

        cylinderLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cylinderLabel2.setForeground(new java.awt.Color(255, 255, 255));
        cylinderLabel2.setText("Cylinder: ");
        cylinderLabel2.setToolTipText("");

        prismLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prismLabel1.setForeground(new java.awt.Color(255, 255, 255));
        prismLabel1.setText("Prism: ");
        prismLabel1.setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(32, 33, 35));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(253, 252, 233)));

        axisLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        axisLabel.setForeground(new java.awt.Color(255, 255, 255));
        axisLabel.setText("Axis: ");
        axisLabel.setToolTipText("");

        sphereOSTXTF.setBackground(new java.awt.Color(135, 206, 250));
        sphereOSTXTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sphereOSTXTF.setForeground(new java.awt.Color(0, 0, 0));
        sphereOSTXTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sphereOSTXTFFocusLost(evt);
            }
        });

        sphereLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sphereLabel.setForeground(new java.awt.Color(255, 255, 255));
        sphereLabel.setText("Sphere: ");
        sphereLabel.setToolTipText("");

        rangeLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        rangeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        rangeLabel1.setText("OS:");
        rangeLabel1.setToolTipText("");

        sphereLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sphereLabel1.setForeground(new java.awt.Color(255, 255, 255));
        sphereLabel1.setText("Measurements: ");
        sphereLabel1.setToolTipText("");

        addOSTXTF.setBackground(new java.awt.Color(135, 206, 250));
        addOSTXTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addOSTXTF.setForeground(new java.awt.Color(0, 0, 0));
        addOSTXTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addOSTXTFFocusLost(evt);
            }
        });

        cylinderLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cylinderLabel3.setForeground(new java.awt.Color(255, 255, 255));
        cylinderLabel3.setText("Cylinder: ");
        cylinderLabel3.setToolTipText("");

        axisOSTXTF.setBackground(new java.awt.Color(135, 206, 250));
        axisOSTXTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        axisOSTXTF.setForeground(new java.awt.Color(0, 0, 0));
        axisOSTXTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                axisOSTXTFFocusLost(evt);
            }
        });

        prismBaseLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prismBaseLabel1.setForeground(new java.awt.Color(255, 255, 255));
        prismBaseLabel1.setText("Prism Base: ");
        prismBaseLabel1.setToolTipText("");

        cylinderOSTXTF.setBackground(new java.awt.Color(135, 206, 250));
        cylinderOSTXTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cylinderOSTXTF.setForeground(new java.awt.Color(0, 0, 0));
        cylinderOSTXTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cylinderOSTXTFFocusLost(evt);
            }
        });

        addLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addLabel1.setForeground(new java.awt.Color(255, 255, 255));
        addLabel1.setText("Add: ");
        addLabel1.setToolTipText("");

        prismOSTXTF.setBackground(new java.awt.Color(135, 206, 250));
        prismOSTXTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prismOSTXTF.setForeground(new java.awt.Color(0, 0, 0));
        prismOSTXTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prismOSTXTFFocusLost(evt);
            }
        });

        prismLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prismLabel2.setForeground(new java.awt.Color(255, 255, 255));
        prismLabel2.setText("Prism: ");
        prismLabel2.setToolTipText("");

        prismBaseOSTXTF.setBackground(new java.awt.Color(135, 206, 250));
        prismBaseOSTXTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prismBaseOSTXTF.setForeground(new java.awt.Color(0, 0, 0));
        prismBaseOSTXTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prismBaseOSTXTFFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(prismBaseLabel1)
                                    .addComponent(addLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prismLabel2)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prismOSTXTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addOSTXTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prismBaseOSTXTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(rangeLabel1))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(sphereLabel1)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cylinderLabel3)
                                    .addComponent(axisLabel)
                                    .addComponent(sphereLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(axisOSTXTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sphereOSTXTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cylinderOSTXTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 71, 71))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rangeLabel1)
                .addGap(3, 3, 3)
                .addComponent(sphereLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sphereLabel)
                    .addComponent(sphereOSTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(axisLabel)
                    .addComponent(axisOSTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cylinderLabel3)
                    .addComponent(cylinderOSTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prismOSTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prismLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(prismBaseLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(prismBaseOSTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addOSTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        sphereLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sphereLabel2.setForeground(new java.awt.Color(255, 255, 255));
        sphereLabel2.setText("Measurements: ");
        sphereLabel2.setToolTipText("");

        sphereODTXTF.setBackground(new java.awt.Color(135, 206, 250));
        sphereODTXTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sphereODTXTF.setForeground(new java.awt.Color(0, 0, 0));
        sphereODTXTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sphereODTXTFFocusLost(evt);
            }
        });
        sphereODTXTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphereODTXTFActionPerformed(evt);
            }
        });

        sphereLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sphereLabel3.setForeground(new java.awt.Color(255, 255, 255));
        sphereLabel3.setText("Sphere: ");
        sphereLabel3.setToolTipText("");

        axisLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        axisLabel1.setForeground(new java.awt.Color(255, 255, 255));
        axisLabel1.setText("Axis: ");
        axisLabel1.setToolTipText("");

        addLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addLabel2.setForeground(new java.awt.Color(255, 255, 255));
        addLabel2.setText("Add: ");
        addLabel2.setToolTipText("");

        axisODTXTF.setBackground(new java.awt.Color(135, 206, 250));
        axisODTXTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        axisODTXTF.setForeground(new java.awt.Color(0, 0, 0));
        axisODTXTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                axisODTXTFFocusLost(evt);
            }
        });

        cylinderODTXTF.setBackground(new java.awt.Color(135, 206, 250));
        cylinderODTXTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cylinderODTXTF.setForeground(new java.awt.Color(0, 0, 0));
        cylinderODTXTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cylinderODTXTFFocusLost(evt);
            }
        });

        prismODTXTF.setBackground(new java.awt.Color(135, 206, 250));
        prismODTXTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prismODTXTF.setForeground(new java.awt.Color(0, 0, 0));
        prismODTXTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prismODTXTFFocusLost(evt);
            }
        });

        prismBaseODTXTF.setBackground(new java.awt.Color(135, 206, 250));
        prismBaseODTXTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prismBaseODTXTF.setForeground(new java.awt.Color(0, 0, 0));
        prismBaseODTXTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prismBaseODTXTFFocusLost(evt);
            }
        });

        addODTXTF.setBackground(new java.awt.Color(135, 206, 250));
        addODTXTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addODTXTF.setForeground(new java.awt.Color(0, 0, 0));
        addODTXTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addODTXTFFocusLost(evt);
            }
        });

        saveBttn1.setBackground(new java.awt.Color(153, 255, 153));
        saveBttn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saveBttn1.setForeground(new java.awt.Color(0, 0, 0));
        saveBttn1.setText("NEXT PAGE");
        saveBttn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBttn1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(addLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addODTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 28, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(axisLabel1)
                                    .addComponent(sphereLabel3)
                                    .addComponent(cylinderLabel2)
                                    .addComponent(prismBaseLabel)
                                    .addComponent(prismLabel1))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sphereODTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(axisODTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cylinderODTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prismODTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prismBaseODTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rangeLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(87, 87, 87))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(sphereLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(saveBttn1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rangeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sphereLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sphereLabel3)
                            .addComponent(sphereODTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(axisLabel1)
                            .addComponent(axisODTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cylinderLabel2)
                            .addComponent(cylinderODTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prismLabel1)
                            .addComponent(prismODTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prismBaseLabel)
                            .addComponent(prismBaseODTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addLabel2)
                            .addComponent(addODTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveBttn1)
                        .addGap(39, 39, 39))))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Input Data for D:");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Input Data for N:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    /****************************
    *     INPUT DATA FRO D sc PH 
    *****************************/

     /**********************************
    *     CORRECTIVE LENSES
    ************************************/
    
    
    /***********************
    *     OS TXT FIELDS
    *************************/
    private void sphereOSTXTFFocusLost(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
       
		Boolean validFloat = validateFloat(sphereODTXTF.getText());
		
		if (!validFloat)
		{
			sphereODTXTF.setText("0.00");
			JOptionPane.showMessageDialog(null, "Enter number in range: 0.00 to 1.00");
			sphereODTXTF.requestFocus(true);
		}
		else
		{
			Double sphereOS = Double.parseDouble(sphereOSTXTF.getText());
			//DecimalFormat dc = new DecimalFormat("0.00");
			//String formattedText = dc.format(sphereOS);
			//sphereODTXTF.setText(formattedText);
			eyeTestResults.setSphereOS(sphereOS);
		}

    }                                      

    private void axisOSTXTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_axisOSTXTFFocusLost
        Boolean validFloat = validateFloat(axisOSTXTF.getText());
		
		if (!validFloat)
		{
			axisOSTXTF.setText("0.00");
			JOptionPane.showMessageDialog(null, "Enter number in range: 0.00 to 1.00");
			axisOSTXTF.requestFocus(true);
		}
		else
		{
         Double axisOS = Double.parseDouble(axisOSTXTF.getText());
         eyeTestResults.setAxisOS(axisOS);
         System.out.println("Axis OS: " + axisOS);
		}
    }//GEN-LAST:event_axisOSTXTFFocusLost

    private void cylinderOSTXTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cylinderOSTXTFFocusLost
        Boolean validFloat = validateFloat(cylinderOSTXTF.getText());
		
		if (!validFloat)
		{
			cylinderOSTXTF.setText("0.00");
			JOptionPane.showMessageDialog(null, "Enter number in range: 0.00 to 1.00");
			cylinderOSTXTF.requestFocus(true);
		}
		else
		{
         Double cylinderOS = Double.parseDouble(cylinderOSTXTF.getText());
         eyeTestResults.setCylinderOS(cylinderOS);
         System.out.println("Cylinder OS: " + cylinderOS);
		}
    }//GEN-LAST:event_cylinderOSTXTFFocusLost

    private void prismOSTXTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prismOSTXTFFocusLost
        Boolean validFloat = validateFloat(prismOSTXTF.getText());
		
		if (!validFloat)
		{
			prismOSTXTF.setText("0.00");
			JOptionPane.showMessageDialog(null, "Enter number in range: 0.00 to 1.00");
			prismOSTXTF.requestFocus(true);
		}
		else
		{
			Double prismOS = Double.parseDouble(prismOSTXTF.getText());
		 
			//DecimalFormat dc = new DecimalFormat("0.00");
			//String formattedText = dc.format(prismOS);
			//prismOSTXTF.setText(formattedText);
			eyeTestResults.setPrismOS(prismOS);
		 
			System.out.println("Prism OS: " + prismOS);
		 
		}
    }//GEN-LAST:event_prismOSTXTFFocusLost

    private void prismBaseOSTXTFFocusLost(java.awt.event.FocusEvent evt) {                                           
        Boolean validFloat = validateFloat(prismBaseOSTXTF.getText());
		
		if (!validFloat)
		{
			prismBaseOSTXTF.setText("0.00");
			JOptionPane.showMessageDialog(null, "Enter number in range: 0.00 to 1.00");
			prismBaseOSTXTF.requestFocus(true);
		}
		else
		{
         Double prismBaseOS = Double.parseDouble(prismBaseOSTXTF.getText());
         eyeTestResults.setPrismBaseOS(prismBaseOS);
         System.out.println("Prism OS: " + prismBaseOS);
		}
    }                                          

    private void addOSTXTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addOSTXTFFocusLost
        Boolean validFloat = validateFloat(addOSTXTF.getText());
		
		if (!validFloat)
		{
			addOSTXTF.setText("0.00");
			JOptionPane.showMessageDialog(null, "Enter number in range: 0.00 to 1.00");
			addOSTXTF.requestFocus(true);
		}
		else
		{
         Double addOS = Double.parseDouble(addOSTXTF.getText());
         eyeTestResults.setAddOS(addOS);
         System.out.println("Add OS: " + addOS);
		}
    }//GEN-LAST:event_addOSTXTFFocusLost

   
    /***********************
    *     OD TXT FIELDS
    *************************/
    private void sphereODTXTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sphereOSTXTFFocusLost
 		Boolean validFloat = validateFloat(sphereODTXTF.getText());
		
		if (!validFloat)
		{
			sphereODTXTF.setText("0.00");
			JOptionPane.showMessageDialog(null, "Enter number in range: 0.00 to 1.00");
			sphereODTXTF.requestFocus(true);
		}
		else
		{
        Double sphereOD = Double.parseDouble(sphereODTXTF.getText());
        eyeTestResults.setSphereOD(sphereOD);
        System.out.println("Sphere OD: " + sphereOD);
		}
    }//GEN-LAST:event_sphereOSTXTFFocusLost

    private void axisODTXTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_axisODTXTFFocusLost
        Boolean validFloat = validateFloat(axisODTXTF.getText());
		
		if (!validFloat)
		{
			axisODTXTF.setText("0.00");
			JOptionPane.showMessageDialog(null, "Enter number in range: 0.00 to 1.00");
			axisODTXTF.requestFocus(true);
		}
		else
		{
        Double axisOD = Double.parseDouble(axisODTXTF.getText());
        eyeTestResults.setAxisOD(axisOD);
        System.out.println("Axis OD: " + axisOD);
		}
    }//GEN-LAST:event_axisODTXTFFocusLost

    private void cylinderODTXTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cylinderODTXTFFocusLost
        Boolean validFloat = validateFloat(cylinderODTXTF.getText());
		
		if (!validFloat)
		{
			cylinderODTXTF.setText("0.00");
			JOptionPane.showMessageDialog(null, "Enter number in range: 0.00 to 1.00");
			cylinderODTXTF.requestFocus(true);
		}
		else
		{
        Double cylinderOD = Double.parseDouble(cylinderODTXTF.getText());
        eyeTestResults.setCylinderOD(cylinderOD);
        System.out.println("Cylinder OD: " + cylinderOD);
		}
    }//GEN-LAST:event_cylinderODTXTFFocusLost

    private void prismODTXTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prismODTXTFFocusLost
        Boolean validFloat = validateFloat(prismODTXTF.getText());
		
		if (!validFloat)
		{
			prismODTXTF.setText("0.00");
			JOptionPane.showMessageDialog(null, "Enter number in range: 0.00 to 1.00");
			prismODTXTF.requestFocus(true);
		}
		else
		{
        Double prismOD = Double.parseDouble(prismODTXTF.getText());
        eyeTestResults.setPrismOD(prismOD);
        System.out.println("Prism OD: " + prismOD);
		}
    }//GEN-LAST:event_prismODTXTFFocusLost

    private void prismBaseODTXTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prismBaseODTXTFFocusLost
        Boolean validFloat = validateFloat(prismBaseODTXTF.getText());
		
		if (!validFloat)
		{
			prismBaseODTXTF.setText("0.00");
			JOptionPane.showMessageDialog(null, "Enter number in range: 0.00 to 1.00");
			prismBaseODTXTF.requestFocus(true);
		}
		else
		{
        Double prismBaseOD = Double.parseDouble(prismBaseODTXTF.getText());
        eyeTestResults.setPrismBaseOD(prismBaseOD);
        System.out.println("Prism OD: " + prismBaseOD);
		}
    }//GEN-LAST:event_prismBaseODTXTFFocusLost

    private void addODTXTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addODTXTFFocusLost
        Boolean validFloat = validateFloat(addODTXTF.getText());
		
		if (!validFloat)
		{
			addODTXTF.setText("0.00");
			JOptionPane.showMessageDialog(null, "Enter number in range: 0.00 to 1.00");
			addODTXTF.requestFocus(true);
		}
		else
		{
         Double addOD = Double.parseDouble(addODTXTF.getText());
         eyeTestResults.setAddOD(addOD);
         System.out.println("Axis OS: " + addOD);
		}
    }//GEN-LAST:event_addODTXTFFocusLost

    
    /*****************************
    *     BUTTONS SAVE AND OCCULAR
    ********************************/
    private void saveBttn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBttn1MouseClicked

        dataBase.save(eyeTestResults);
		mainDash.showOccularExResults();
    }//GEN-LAST:event_saveBttn1MouseClicked

    private void dccODComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dccODComboBoxActionPerformed
        eyeTestResults.setDccOD(dccODComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dccODComboBoxActionPerformed

    private void dccOSComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dccOSComboBoxActionPerformed
        eyeTestResults.setDccOS(dccOSComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dccOSComboBoxActionPerformed

    private void dccOUComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dccOUComboBoxActionPerformed
        eyeTestResults.setDccOU(dccOUComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dccOUComboBoxActionPerformed

    private void dscODComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dscODComboBoxActionPerformed
        eyeTestResults.setDscOD(dscODComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dscODComboBoxActionPerformed

    private void dscOSComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dscOSComboBoxActionPerformed
        eyeTestResults.setDscOS(dscOSComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dscOSComboBoxActionPerformed

    private void dscOUComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dscOUComboBoxActionPerformed
        eyeTestResults.setDscOU(dscOUComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dscOUComboBoxActionPerformed

    private void dccODphComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dccODphComboBoxActionPerformed
        eyeTestResults.setDccODph(dccODphComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dccODphComboBoxActionPerformed

    private void dccOSphComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dccOSphComboBoxActionPerformed
        eyeTestResults.setDccOSph(dccOSphComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dccOSphComboBoxActionPerformed

    private void dccOUphComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dccOUphComboBoxActionPerformed
        eyeTestResults.setDccOUph(dccOUphComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dccOUphComboBoxActionPerformed

    private void dscODphComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dscODphComboBoxActionPerformed
        eyeTestResults.setDscODph(dscODphComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dscODphComboBoxActionPerformed

    private void dscOUphComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dscOUphComboBoxActionPerformed
        eyeTestResults.setDscOUph(dscOUphComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dscOUphComboBoxActionPerformed

    private void dscOSphComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dscOSphComboBoxActionPerformed
        eyeTestResults.setDscOSph(dscOSphComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dscOSphComboBoxActionPerformed

    private void nccODComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nccODComboBoxActionPerformed
        eyeTestResults.setNccOD(nccODComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_nccODComboBoxActionPerformed

    private void nccOSComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nccOSComboBoxActionPerformed
        eyeTestResults.setNccOS(nccOSComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_nccOSComboBoxActionPerformed

    private void nccOUComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nccOUComboBoxActionPerformed
        eyeTestResults.setNccOU(nccOUComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_nccOUComboBoxActionPerformed

    private void nscODComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nscODComboBoxActionPerformed
        eyeTestResults.setNscOD(nscODComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_nscODComboBoxActionPerformed

    private void nscOSComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nscOSComboBoxActionPerformed
        eyeTestResults.setNscOS(nscOSComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_nscOSComboBoxActionPerformed

    private void nscOUComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nscOUComboBoxActionPerformed
        eyeTestResults.setNscOU(nscOUComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_nscOUComboBoxActionPerformed

    private void nccODphComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nccODphComboBoxActionPerformed
        eyeTestResults.setNccODph(nccODphComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_nccODphComboBoxActionPerformed

    private void nccOSphComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nccOSphComboBoxActionPerformed
        eyeTestResults.setNccOSph(nccOSphComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_nccOSphComboBoxActionPerformed

    private void nccOUphComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nccOUphComboBoxActionPerformed
        eyeTestResults.setNccOUph(nccOUphComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_nccOUphComboBoxActionPerformed

    private void nscODphComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nscODphComboBoxActionPerformed
        eyeTestResults.setNscODph(nscODphComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_nscODphComboBoxActionPerformed

    private void nscOUphComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nscOUphComboBoxActionPerformed
        eyeTestResults.setNscOUph(nscOUphComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_nscOUphComboBoxActionPerformed

    private void nscOSphComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nscOSphComboBoxActionPerformed
        eyeTestResults.setNscOSph(nscOSphComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_nscOSphComboBoxActionPerformed

    private void sphereODTXTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphereODTXTFActionPerformed
        System.out.println("here");
    }//GEN-LAST:event_sphereODTXTFActionPerformed

    private void occularBttnMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        mainDash.showOccularExResults();
    }//GEN-LAS

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLabel1;
    private javax.swing.JLabel addLabel2;
    private javax.swing.JTextField addODTXTF;
    private javax.swing.JTextField addOSTXTF;
    private javax.swing.JLabel axisLabel;
    private javax.swing.JLabel axisLabel1;
    private javax.swing.JTextField axisODTXTF;
    private javax.swing.JTextField axisOSTXTF;
    private javax.swing.JLabel correctiveLabel;
    private javax.swing.JLabel cylinderLabel2;
    private javax.swing.JLabel cylinderLabel3;
    private javax.swing.JTextField cylinderODTXTF;
    private javax.swing.JTextField cylinderOSTXTF;
    private javax.swing.JComboBox<String> dccODComboBox;
    private javax.swing.JComboBox<String> dccODphComboBox;
    private javax.swing.JComboBox<String> dccOSComboBox;
    private javax.swing.JComboBox<String> dccOSphComboBox;
    private javax.swing.JComboBox<String> dccOUComboBox;
    private javax.swing.JComboBox<String> dccOUphComboBox;
    private javax.swing.JComboBox<String> dscODComboBox;
    private javax.swing.JComboBox<String> dscODphComboBox;
    private javax.swing.JComboBox<String> dscOSComboBox;
    private javax.swing.JComboBox<String> dscOSphComboBox;
    private javax.swing.JComboBox<String> dscOUComboBox;
    private javax.swing.JComboBox<String> dscOUphComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JComboBox<String> nccODComboBox;
    private javax.swing.JComboBox<String> nccODphComboBox;
    private javax.swing.JComboBox<String> nccOSComboBox;
    private javax.swing.JComboBox<String> nccOSphComboBox;
    private javax.swing.JComboBox<String> nccOUComboBox;
    private javax.swing.JComboBox<String> nccOUphComboBox;
    private javax.swing.JComboBox<String> nscODComboBox;
    private javax.swing.JComboBox<String> nscODphComboBox;
    private javax.swing.JComboBox<String> nscOSComboBox;
    private javax.swing.JComboBox<String> nscOSphComboBox;
    private javax.swing.JComboBox<String> nscOUComboBox;
    private javax.swing.JComboBox<String> nscOUphComboBox;
    private javax.swing.JLabel prismBaseLabel;
    private javax.swing.JLabel prismBaseLabel1;
    private javax.swing.JTextField prismBaseODTXTF;
    private javax.swing.JTextField prismBaseOSTXTF;
    private javax.swing.JLabel prismLabel1;
    private javax.swing.JLabel prismLabel2;
    private javax.swing.JTextField prismODTXTF;
    private javax.swing.JTextField prismOSTXTF;
    private javax.swing.JLabel rangeLabel;
    private javax.swing.JLabel rangeLabel1;
    private javax.swing.JButton saveBttn1;
    private javax.swing.JLabel sphereLabel;
    private javax.swing.JLabel sphereLabel1;
    private javax.swing.JLabel sphereLabel2;
    private javax.swing.JLabel sphereLabel3;
    private javax.swing.JTextField sphereODTXTF;
    private javax.swing.JTextField sphereOSTXTF;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
