/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs499_ophthalmology_emr;
//import  java.awt.TextField;
/**
 *
 * @author angelaallison
 */
public class VisualAcuity extends javax.swing.JPanel {
    
    private MainDashboard mainDash;
    private DataBaseManager dataBase;
    private EyeTestResults eyeTestResults;
    private Patient activePatient;
    private Appointment activeAppointment;
         
    public VisualAcuity(MainDashboard mD ) {
     
     activePatient = null;
     mainDash = mD;
     dataBase = DataBaseManager.getInstance();
    
     initComponents();
     
    }
    public void loadEyeTestResults(){
        
        activePatient = mainDash.getActivePatient();
        activeAppointment = mainDash.getActiveAppointment();
        eyeTestResults = dataBase.getNewEyeTestResults(activePatient.getPatientID(), activeAppointment.getApptID());
 
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        measurementTXTField = new javax.swing.JTextField();
        visualTXTField = new javax.swing.JTextField();
        pinholeTXTField = new javax.swing.JTextField();
        indcatorLabel = new javax.swing.JLabel();
        measurementLabel = new javax.swing.JLabel();
        pinholeLabel = new javax.swing.JLabel();
        visualAcuityLabel = new javax.swing.JLabel();
        ccRadioBttn = new javax.swing.JRadioButton();
        scRadioBttn = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        nearCheckBox1 = new javax.swing.JCheckBox();
        correctiveLPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vAcuityLabel = new javax.swing.JLabel();
        lenseTXTField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lenseLabel1 = new javax.swing.JLabel();
        vAcuityTXTFeild = new javax.swing.JTextField();
        vTangeLabel = new javax.swing.JLabel();
        mRangeLabel1 = new javax.swing.JLabel();
        mRangeTXTFeild1 = new javax.swing.JTextField();
        selectionLabel = new javax.swing.JLabel();
        nearDistanceBttn = new javax.swing.JButton();
        farDistanceBttn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        indcatorLabel1 = new javax.swing.JLabel();
        ccRadioBttn1 = new javax.swing.JRadioButton();
        scRadioBttn1 = new javax.swing.JRadioButton();
        measurementLabel2 = new javax.swing.JLabel();
        measurementTXTField2 = new javax.swing.JTextField();
        visualAcuityLabel2 = new javax.swing.JLabel();
        visualTXTField2 = new javax.swing.JTextField();
        pinholeLabel2 = new javax.swing.JLabel();
        pinholeTXTField2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        nearCheckBox = new javax.swing.JCheckBox();
        submitButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(57, 113, 177));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setPreferredSize(new java.awt.Dimension(1630, 896));

        titleBar.setBackground(new java.awt.Color(32, 33, 35));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Visual Acuity");

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 5, 4, 5, new java.awt.Color(253, 252, 233)));
        jPanel1.setPreferredSize(new java.awt.Dimension(405, 47));

        measurementTXTField.setBackground(new java.awt.Color(253, 252, 233));
        measurementTXTField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        measurementTXTField.setForeground(new java.awt.Color(0, 0, 0));
        measurementTXTField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                measurementTXTFieldFocusLost(evt);
            }
        });

        visualTXTField.setBackground(new java.awt.Color(253, 252, 233));
        visualTXTField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        visualTXTField.setForeground(new java.awt.Color(0, 0, 0));
        visualTXTField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                visualTXTFieldFocusLost(evt);
            }
        });
        visualTXTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualTXTFieldActionPerformed(evt);
            }
        });

        pinholeTXTField.setBackground(new java.awt.Color(253, 252, 233));
        pinholeTXTField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pinholeTXTField.setForeground(new java.awt.Color(0, 0, 0));
        pinholeTXTField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pinholeTXTFieldFocusLost(evt);
            }
        });

        indcatorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        indcatorLabel.setForeground(new java.awt.Color(255, 255, 255));
        indcatorLabel.setText("Indicator:");

        measurementLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        measurementLabel.setForeground(new java.awt.Color(255, 255, 255));
        measurementLabel.setText("Measurement:");

        pinholeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pinholeLabel.setForeground(new java.awt.Color(255, 255, 255));
        pinholeLabel.setText("Pinhole:");

        visualAcuityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        visualAcuityLabel.setForeground(new java.awt.Color(255, 255, 255));
        visualAcuityLabel.setText("Visual Acuity:");

        ccRadioBttn.setBackground(new java.awt.Color(32, 33, 35));
        ccRadioBttn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ccRadioBttn.setForeground(new java.awt.Color(255, 255, 255));
        ccRadioBttn.setText("cc");
        ccRadioBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccRadioBttnActionPerformed(evt);
            }
        });

        scRadioBttn.setBackground(new java.awt.Color(32, 33, 35));
        scRadioBttn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        scRadioBttn.setForeground(new java.awt.Color(255, 255, 255));
        scRadioBttn.setText("sc");

        jPanel6.setBackground(new java.awt.Color(135, 206, 250));

        nearCheckBox1.setBackground(new java.awt.Color(135, 206, 250));
        nearCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nearCheckBox1.setForeground(new java.awt.Color(32, 33, 35));
        nearCheckBox1.setText("Far Distance");
        nearCheckBox1.setToolTipText("");
        nearCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nearCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(nearCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(nearCheckBox1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ccRadioBttn)
                        .addGap(41, 41, 41)
                        .addComponent(scRadioBttn))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(measurementTXTField)
                        .addComponent(visualTXTField)
                        .addComponent(pinholeTXTField)
                        .addComponent(indcatorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(measurementLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                        .addComponent(pinholeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(visualAcuityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(indcatorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccRadioBttn)
                    .addComponent(scRadioBttn))
                .addGap(36, 36, 36)
                .addComponent(measurementLabel)
                .addGap(18, 18, 18)
                .addComponent(measurementTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(visualAcuityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(visualTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(pinholeLabel)
                .addGap(18, 18, 18)
                .addComponent(pinholeTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        correctiveLPanel.setBackground(new java.awt.Color(32, 33, 35));
        correctiveLPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 5, 4, 5, new java.awt.Color(253, 252, 233)));

        jPanel3.setBackground(new java.awt.Color(135, 206, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 33, 35));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Corrective Lenses");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        vAcuityLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vAcuityLabel.setForeground(new java.awt.Color(255, 255, 255));
        vAcuityLabel.setText("Visual Acuity:");
        vAcuityLabel.setToolTipText("");

        lenseTXTField.setBackground(new java.awt.Color(253, 252, 233));
        lenseTXTField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lenseTXTField.setForeground(new java.awt.Color(0, 0, 0));
        lenseTXTField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lenseTXTFieldFocusLost(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(132, 206, 250));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(32, 33, 35));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sphere", "Cylinder", "Axis", "Add", "Prisim", "Prisim Base" }));

        lenseLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lenseLabel1.setForeground(new java.awt.Color(255, 255, 255));
        lenseLabel1.setText("Lenses:");

        vAcuityTXTFeild.setBackground(new java.awt.Color(253, 252, 233));
        vAcuityTXTFeild.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vAcuityTXTFeild.setForeground(new java.awt.Color(0, 0, 0));

        vTangeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vTangeLabel.setForeground(new java.awt.Color(255, 255, 255));
        vTangeLabel.setText("(0.00 - 1.00)");

        mRangeLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mRangeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        mRangeLabel1.setText("Measurement Range:");

        mRangeTXTFeild1.setBackground(new java.awt.Color(253, 252, 233));
        mRangeTXTFeild1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mRangeTXTFeild1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout correctiveLPanelLayout = new javax.swing.GroupLayout(correctiveLPanel);
        correctiveLPanel.setLayout(correctiveLPanelLayout);
        correctiveLPanelLayout.setHorizontalGroup(
            correctiveLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(correctiveLPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(correctiveLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mRangeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vAcuityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lenseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(correctiveLPanelLayout.createSequentialGroup()
                        .addComponent(lenseTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(correctiveLPanelLayout.createSequentialGroup()
                        .addComponent(mRangeTXTFeild1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(vTangeLabel))
                    .addComponent(vAcuityTXTFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        correctiveLPanelLayout.setVerticalGroup(
            correctiveLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(correctiveLPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(lenseLabel1)
                .addGap(18, 18, 18)
                .addGroup(correctiveLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lenseTXTField)
                    .addComponent(jComboBox1))
                .addGap(63, 63, 63)
                .addComponent(mRangeLabel1)
                .addGroup(correctiveLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(correctiveLPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vTangeLabel))
                    .addGroup(correctiveLPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(mRangeTXTFeild1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(vAcuityLabel)
                .addGap(18, 18, 18)
                .addComponent(vAcuityTXTFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        selectionLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        selectionLabel.setForeground(new java.awt.Color(255, 255, 255));
        selectionLabel.setText("Select Distance:");

        nearDistanceBttn.setBackground(new java.awt.Color(135, 206, 250));
        nearDistanceBttn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        nearDistanceBttn.setForeground(new java.awt.Color(0, 0, 0));
        nearDistanceBttn.setText("NEAR");

        farDistanceBttn.setBackground(new java.awt.Color(135, 206, 250));
        farDistanceBttn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        farDistanceBttn.setForeground(new java.awt.Color(0, 0, 0));
        farDistanceBttn.setText("FAR");
        farDistanceBttn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                farDistanceBttnFocusLost(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(32, 33, 35));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 5, 4, 5, new java.awt.Color(253, 252, 233)));

        indcatorLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        indcatorLabel1.setForeground(new java.awt.Color(255, 255, 255));
        indcatorLabel1.setText("Indicator:");

        ccRadioBttn1.setBackground(new java.awt.Color(32, 33, 35));
        ccRadioBttn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ccRadioBttn1.setForeground(new java.awt.Color(255, 255, 255));
        ccRadioBttn1.setText("cc");
        ccRadioBttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccRadioBttn1ActionPerformed(evt);
            }
        });

        scRadioBttn1.setBackground(new java.awt.Color(32, 33, 35));
        scRadioBttn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        scRadioBttn1.setForeground(new java.awt.Color(255, 255, 255));
        scRadioBttn1.setText("sc");

        measurementLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        measurementLabel2.setForeground(new java.awt.Color(255, 255, 255));
        measurementLabel2.setText("Measurement:");

        measurementTXTField2.setBackground(new java.awt.Color(253, 252, 233));
        measurementTXTField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        measurementTXTField2.setForeground(new java.awt.Color(0, 0, 0));
        measurementTXTField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                measurementTXTField2FocusLost(evt);
            }
        });

        visualAcuityLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        visualAcuityLabel2.setForeground(new java.awt.Color(255, 255, 255));
        visualAcuityLabel2.setText("Visual Acuity:");

        visualTXTField2.setBackground(new java.awt.Color(253, 252, 233));
        visualTXTField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        visualTXTField2.setForeground(new java.awt.Color(0, 0, 0));
        visualTXTField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                visualTXTField2FocusLost(evt);
            }
        });
        visualTXTField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualTXTField2ActionPerformed(evt);
            }
        });

        pinholeLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pinholeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        pinholeLabel2.setText("Pinhole:");

        pinholeTXTField2.setBackground(new java.awt.Color(253, 252, 233));
        pinholeTXTField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pinholeTXTField2.setForeground(new java.awt.Color(0, 0, 0));
        pinholeTXTField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pinholeTXTField2FocusLost(evt);
            }
        });
        pinholeTXTField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinholeTXTField2ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(135, 206, 250));

        nearCheckBox.setBackground(new java.awt.Color(135, 206, 250));
        nearCheckBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nearCheckBox.setForeground(new java.awt.Color(32, 33, 35));
        nearCheckBox.setText("Near Distance");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nearCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nearCheckBox)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indcatorLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(measurementLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pinholeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pinholeTXTField2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(ccRadioBttn1)
                                    .addGap(41, 41, 41)
                                    .addComponent(scRadioBttn1))
                                .addComponent(measurementTXTField2)
                                .addComponent(visualAcuityLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                .addComponent(visualTXTField2)))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(indcatorLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccRadioBttn1)
                    .addComponent(scRadioBttn1))
                .addGap(36, 36, 36)
                .addComponent(measurementLabel2)
                .addGap(18, 18, 18)
                .addComponent(measurementTXTField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(visualAcuityLabel2)
                .addGap(18, 18, 18)
                .addComponent(visualTXTField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pinholeLabel2)
                .addGap(18, 18, 18)
                .addComponent(pinholeTXTField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        submitButton.setBackground(new java.awt.Color(153, 255, 153));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(0, 0, 0));
        submitButton.setText("SUMBIT");
        submitButton.setActionCommand("SUBMIT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(selectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(farDistanceBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(nearDistanceBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correctiveLPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectionLabel)
                    .addComponent(farDistanceBttn)
                    .addComponent(nearDistanceBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(correctiveLPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void farDistanceBttnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_farDistanceBttnFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_farDistanceBttnFocusLost

    private void nearCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nearCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nearCheckBox1ActionPerformed

    private void measurementTXTFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_measurementTXTFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_measurementTXTFieldFocusLost

    private void visualTXTFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_visualTXTFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_visualTXTFieldFocusLost

    private void pinholeTXTFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pinholeTXTFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pinholeTXTFieldFocusLost

    private void ccRadioBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccRadioBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccRadioBttnActionPerformed

    private void visualTXTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualTXTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visualTXTFieldActionPerformed

    private void ccRadioBttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccRadioBttn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccRadioBttn1ActionPerformed

    private void measurementTXTField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_measurementTXTField2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_measurementTXTField2FocusLost

    private void visualTXTField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_visualTXTField2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_visualTXTField2FocusLost

    private void visualTXTField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualTXTField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visualTXTField2ActionPerformed

    private void pinholeTXTField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pinholeTXTField2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pinholeTXTField2FocusLost

    private void pinholeTXTField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinholeTXTField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinholeTXTField2ActionPerformed

    private void lenseTXTFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lenseTXTFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lenseTXTFieldFocusLost

    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ccRadioBttn;
    private javax.swing.JRadioButton ccRadioBttn1;
    private javax.swing.JPanel correctiveLPanel;
    private javax.swing.JButton farDistanceBttn;
    private javax.swing.JLabel indcatorLabel;
    private javax.swing.JLabel indcatorLabel1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lenseLabel1;
    private javax.swing.JTextField lenseTXTField;
    private javax.swing.JLabel mRangeLabel1;
    private javax.swing.JTextField mRangeTXTFeild1;
    private javax.swing.JLabel measurementLabel;
    private javax.swing.JLabel measurementLabel2;
    private javax.swing.JTextField measurementTXTField;
    private javax.swing.JTextField measurementTXTField2;
    private javax.swing.JCheckBox nearCheckBox;
    private javax.swing.JCheckBox nearCheckBox1;
    private javax.swing.JButton nearDistanceBttn;
    private javax.swing.JLabel pinholeLabel;
    private javax.swing.JLabel pinholeLabel2;
    private javax.swing.JTextField pinholeTXTField;
    private javax.swing.JTextField pinholeTXTField2;
    private javax.swing.JRadioButton scRadioBttn;
    private javax.swing.JRadioButton scRadioBttn1;
    private javax.swing.JLabel selectionLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel vAcuityLabel;
    private javax.swing.JTextField vAcuityTXTFeild;
    private javax.swing.JLabel vTangeLabel;
    private javax.swing.JLabel visualAcuityLabel;
    private javax.swing.JLabel visualAcuityLabel2;
    private javax.swing.JTextField visualTXTField;
    private javax.swing.JTextField visualTXTField2;
    // End of variables declaration//GEN-END:variables
}
